[2024-06-28T10:25:23.636+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T10:25:23.654+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preprocess_data.preprocess_stock_data manual__2024-06-28T10:15:20.156528+00:00 [queued]>
[2024-06-28T10:25:23.661+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preprocess_data.preprocess_stock_data manual__2024-06-28T10:15:20.156528+00:00 [queued]>
[2024-06-28T10:25:23.661+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-28T10:25:23.668+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): preprocess_stock_data> on 2024-06-28 10:15:20.156528+00:00
[2024-06-28T10:25:23.675+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=51) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-28T10:25:23.677+0000] {standard_task_runner.py:63} INFO - Started process 57 to run task
[2024-06-28T10:25:23.678+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'preprocess_data', 'preprocess_stock_data', 'manual__2024-06-28T10:15:20.156528+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/preprocess_data.py', '--cfg-path', '/tmp/tmpb3fmouo9']
[2024-06-28T10:25:23.681+0000] {standard_task_runner.py:91} INFO - Job 43: Subtask preprocess_stock_data
[2024-06-28T10:25:23.692+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-06-28T10:25:23.720+0000] {task_command.py:426} INFO - Running <TaskInstance: preprocess_data.preprocess_stock_data manual__2024-06-28T10:15:20.156528+00:00 [running]> on host eb8c7fbba7b2
[2024-06-28T10:25:23.772+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='preprocess_data' AIRFLOW_CTX_TASK_ID='preprocess_stock_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T10:15:20.156528+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-28T10:15:20.156528+00:00'
[2024-06-28T10:25:23.773+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T10:25:23.782+0000] {preprocess_data.py:22} INFO - Reading data from /opt/***/data/data.csv
[2024-06-28T10:25:23.785+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T10:25:23.785+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/preprocess_data.py", line 23, in preprocess_data
    df = pd.read_csv(file_path)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 617, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1748, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 843, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 904, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 879, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 890, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2058, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 7 fields in line 148, saw 8

[2024-06-28T10:25:23.794+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=preprocess_data, task_id=preprocess_stock_data, run_id=manual__2024-06-28T10:15:20.156528+00:00, execution_date=20240628T101520, start_date=20240628T102523, end_date=20240628T102523
[2024-06-28T10:25:23.800+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 43 for task preprocess_stock_data (Error tokenizing data. C error: Expected 7 fields in line 148, saw 8
; 57)
[2024-06-28T10:25:23.812+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-28T10:25:23.822+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T10:25:23.823+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
