[2024-06-28T01:17:58.139+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T01:17:58.169+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preprocess_data.preprocess_stock_data scheduled__2024-06-27T00:00:00+00:00 [queued]>
[2024-06-28T01:17:58.178+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preprocess_data.preprocess_stock_data scheduled__2024-06-27T00:00:00+00:00 [queued]>
[2024-06-28T01:17:58.179+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T01:17:58.190+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): preprocess_stock_data> on 2024-06-27 00:00:00+00:00
[2024-06-28T01:17:58.200+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=56) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-28T01:17:58.203+0000] {standard_task_runner.py:63} INFO - Started process 69 to run task
[2024-06-28T01:17:58.204+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'preprocess_data', 'preprocess_stock_data', 'scheduled__2024-06-27T00:00:00+00:00', '--job-id', '939', '--raw', '--subdir', 'DAGS_FOLDER/preprocess_data.py', '--cfg-path', '/tmp/tmpa7sw01ic']
[2024-06-28T01:17:58.209+0000] {standard_task_runner.py:91} INFO - Job 939: Subtask preprocess_stock_data
[2024-06-28T01:17:58.228+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-06-28T01:17:58.306+0000] {task_command.py:426} INFO - Running <TaskInstance: preprocess_data.preprocess_stock_data scheduled__2024-06-27T00:00:00+00:00 [running]> on host 5daea60ed64a
[2024-06-28T01:17:58.311+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:356: DeprecationWarning: The sql_engine_encoding option in [core] has been moved to the sql_engine_encoding option in [database] - the old setting has been used, but please update your config.
  engine_args["encoding"] = conf.get("database", "SQL_ENGINE_ENCODING", fallback="utf-8")

[2024-06-28T01:17:58.517+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='preprocess_data' AIRFLOW_CTX_TASK_ID='preprocess_stock_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-27T00:00:00+00:00'
[2024-06-28T01:17:58.519+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T01:17:58.542+0000] {preprocess_data.py:22} INFO - Reading data from /opt/***/data/data.csv
[2024-06-28T01:17:58.618+0000] {preprocess_data.py:28} INFO - Normalized data saved to /opt/***/data/data_normalized.csv
[2024-06-28T01:17:58.619+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T01:17:58.621+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T01:17:58.646+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=preprocess_data, task_id=preprocess_stock_data, run_id=scheduled__2024-06-27T00:00:00+00:00, execution_date=20240627T000000, start_date=20240628T011758, end_date=20240628T011758
[2024-06-28T01:17:58.747+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T01:17:58.780+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T01:17:58.788+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T10:15:18.589+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T10:15:18.605+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preprocess_data.preprocess_stock_data scheduled__2024-06-27T00:00:00+00:00 [queued]>
[2024-06-28T10:15:18.610+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preprocess_data.preprocess_stock_data scheduled__2024-06-27T00:00:00+00:00 [queued]>
[2024-06-28T10:15:18.610+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T10:15:18.616+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): preprocess_stock_data> on 2024-06-27 00:00:00+00:00
[2024-06-28T10:15:18.623+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=52) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-28T10:15:18.625+0000] {standard_task_runner.py:63} INFO - Started process 58 to run task
[2024-06-28T10:15:18.625+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'preprocess_data', 'preprocess_stock_data', 'scheduled__2024-06-27T00:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/preprocess_data.py', '--cfg-path', '/tmp/tmpldh58nve']
[2024-06-28T10:15:18.627+0000] {standard_task_runner.py:91} INFO - Job 37: Subtask preprocess_stock_data
[2024-06-28T10:15:18.641+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-06-28T10:15:18.685+0000] {task_command.py:426} INFO - Running <TaskInstance: preprocess_data.preprocess_stock_data scheduled__2024-06-27T00:00:00+00:00 [running]> on host 0d0315ca3a10
[2024-06-28T10:15:18.687+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:356: DeprecationWarning: The sql_engine_encoding option in [core] has been moved to the sql_engine_encoding option in [database] - the old setting has been used, but please update your config.
  engine_args["encoding"] = conf.get("database", "SQL_ENGINE_ENCODING", fallback="utf-8")

[2024-06-28T10:15:18.759+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='preprocess_data' AIRFLOW_CTX_TASK_ID='preprocess_stock_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-27T00:00:00+00:00'
[2024-06-28T10:15:18.760+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T10:15:18.771+0000] {preprocess_data.py:22} INFO - Reading data from /opt/***/data/data.csv
[2024-06-28T10:15:18.774+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T10:15:18.775+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/preprocess_data.py", line 23, in preprocess_data
    df = pd.read_csv(file_path)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 617, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1748, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 843, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 904, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 879, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 890, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2058, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 7 fields in line 148, saw 8

[2024-06-28T10:15:18.787+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=preprocess_data, task_id=preprocess_stock_data, run_id=scheduled__2024-06-27T00:00:00+00:00, execution_date=20240627T000000, start_date=20240628T101518, end_date=20240628T101518
[2024-06-28T10:15:18.797+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 37 for task preprocess_stock_data (Error tokenizing data. C error: Expected 7 fields in line 148, saw 8
; 58)
[2024-06-28T10:15:18.840+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-28T10:15:18.853+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T10:15:18.854+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
