[2024-06-27T18:17:14.254+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T18:17:14.279+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_model.train_stock_model manual__2024-06-27T18:17:10.987851+00:00 [queued]>
[2024-06-27T18:17:14.284+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_model.train_stock_model manual__2024-06-27T18:17:10.987851+00:00 [queued]>
[2024-06-27T18:17:14.284+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-27T18:17:14.291+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_stock_model> on 2024-06-27 18:17:10.987851+00:00
[2024-06-27T18:17:14.304+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=44) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-27T18:17:14.305+0000] {standard_task_runner.py:63} INFO - Started process 49 to run task
[2024-06-27T18:17:14.306+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'train_model', 'train_stock_model', 'manual__2024-06-27T18:17:10.987851+00:00', '--job-id', '398', '--raw', '--subdir', 'DAGS_FOLDER/train_model.py', '--cfg-path', '/tmp/tmp1nsjay47']
[2024-06-27T18:17:14.308+0000] {standard_task_runner.py:91} INFO - Job 398: Subtask train_stock_model
[2024-06-27T18:17:14.328+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-06-27T18:17:14.354+0000] {task_command.py:426} INFO - Running <TaskInstance: train_model.train_stock_model manual__2024-06-27T18:17:10.987851+00:00 [running]> on host 5daea60ed64a
[2024-06-27T18:17:14.418+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='train_model' AIRFLOW_CTX_TASK_ID='train_stock_model' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T18:17:10.987851+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-27T18:17:10.987851+00:00'
[2024-06-27T18:17:14.419+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T18:17:14.704+0000] {logging_mixin.py:188} WARNING - train loop:   0%|          | 0/300 [00:00<?, ?it/s]
[2024-06-27T18:17:14.709+0000] {logging_mixin.py:188} WARNING - train loop:   0%|          | 0/300 [00:00<?, ?it/s]
[2024-06-27T18:17:14.710+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T18:17:14.710+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/train_model.py", line 67, in train_model
    logits, *last_states = modelnn.model([batch_x] + init_states)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/layers/layer.py", line 1537, in __init__
    raise ValueError(
ValueError: In a nested call() argument, you cannot mix tensors and non-tensors. Received invalid mixed argument: inputs=[array([[[0.44629383],
        [0.4693246 ],
        [0.4759047 ],
        [0.5606737 ],
        [0.5314498 ],
        [0.50958014],
        [0.5188699 ],
        [0.49700022],
        [0.45693827],
        [0.44668102]]]), <tf.Tensor: shape=(1, 128), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
      dtype=float32)>, <tf.Tensor: shape=(1, 128), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
      dtype=float32)>]
[2024-06-27T18:17:14.733+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=train_model, task_id=train_stock_model, run_id=manual__2024-06-27T18:17:10.987851+00:00, execution_date=20240627T181710, start_date=20240627T181714, end_date=20240627T181714
[2024-06-27T18:17:14.750+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 398 for task train_stock_model (In a nested call() argument, you cannot mix tensors and non-tensors. Received invalid mixed argument: inputs=[array([[[0.44629383],
        [0.4693246 ],
        [0.4759047 ],
        [0.5606737 ],
        [0.5314498 ],
        [0.50958014],
        [0.5188699 ],
        [0.49700022],
        [0.45693827],
        [0.44668102]]]), <tf.Tensor: shape=(1, 128), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
      dtype=float32)>, <tf.Tensor: shape=(1, 128), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
      dtype=float32)>]; 49)
[2024-06-27T18:17:14.803+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-27T18:17:14.820+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T18:17:14.821+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
