[2024-06-28T10:33:04.160+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T10:33:04.394+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: make_predictions.make_predictions_task manual__2024-06-28T10:32:47.828549+00:00 [queued]>
[2024-06-28T10:33:04.545+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: make_predictions.make_predictions_task manual__2024-06-28T10:32:47.828549+00:00 [queued]>
[2024-06-28T10:33:04.561+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T10:33:04.683+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): make_predictions_task> on 2024-06-28 10:32:47.828549+00:00
[2024-06-28T10:33:04.720+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2486) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-28T10:33:04.716+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'make_predictions', 'make_predictions_task', 'manual__2024-06-28T10:32:47.828549+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/make_predictions.py', '--cfg-path', '/tmp/tmpghfbyfwy']
[2024-06-28T10:33:04.749+0000] {standard_task_runner.py:91} INFO - Job 47: Subtask make_predictions_task
[2024-06-28T10:33:04.749+0000] {standard_task_runner.py:63} INFO - Started process 2492 to run task
[2024-06-28T10:33:09.117+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-06-28T10:33:30.536+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 47 for task make_predictions_task ((psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8); 2492)
[2024-06-28T10:33:42.955+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-28T10:33:43.065+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T10:33:43.069+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
